### ISSUE TITLE
Error when run script

### ISSUE THREAD

**Issue by ghost** [stefantalpalaru/generate_HLS#1]
```
root@av247:~# ./generate_HLS.py "test-1080p.mp4" 720 480
Traceback (most recent call last):
  File "./generate_HLS.py", line 210, in <module>
    data = convert_to_mp4(args.in_file, mp4_name, height)
  File "./generate_HLS.py", line 140, in convert_to_mp4
    pprint(traceback.format_exc(), data['output'])
  File "/usr/lib/python2.7/pprint.py", line 59, in pprint
    printer.pprint(object)
  File "/usr/lib/python2.7/pprint.py", line 117, in pprint
    self._format(object, self._stream, 0, 0, {}, 0)
  File "/usr/lib/python2.7/pprint.py", line 143, in _format
    write = stream.write
AttributeError: 'str' object has no attribute 'write'
```

**Comment by stefantalpalaru** [comment]
Fixed. Thanks.

**Comment by ghost** [comment]
```
root@av247:~# ./generate_HLS.py "/home/data/test-1080p.mp4" 720 480
['Traceback (most recent call last):\n  File "./generate_HLS.py", line 137, in convert_to_mp4\n    data[\'output\'] += subprocess.check_output(cmd, stderr=subprocess.STDOUT)\n  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output\n    raise CalledProcessError(retcode, cmd, output=output)\nCalledProcessError: Command \'[\'ffmpeg\', \'-y\', \'-i\', \'/home/data/test-1080p.mp4\', \'-c:a\', \'libfdk_aac\', \'-vbr\', \'3\', \'-c:v\', \'libx264\', \'-crf\', \'25\', \'-movflags\', \'faststart\', \'-profile:v\', \'baseline\', \'-pix_fmt\', \'yuv420p\', \'-ar\', \'44100\', \'-sws_flags\', \'lanczos\', \'-vf\', \'scale=-2:720\', \'/home/data/test-1080p_720p.mp4\']\' returned non-zero exit status 1\n',
 '']
{'error': True, 'output': ''}
```

**Comment by stefantalpalaru** [comment]
Does "/home/data/test-1080p.mp4" exist? Do you have "ffmpeg" installed?

What's the output of the command line that's being executed there?

`ffmpeg -y -i /home/data/test-1080p.mp4 -c:a libfdk_aac -vbr 3 -c:v libx264 -crf 25 -movflags faststart -profile:v baseline -pix_fmt yuv420p -ar 44100 -sws_flags lanczos -vf scale=-2:720 /home/data/test-1080p_720p.mp4`

**Comment by ghost** [comment]
Hello,

"/home/data/test-1080p.mp4" are exist. FFMPEG have installed.

```
root@av247:~# ffmpeg -y -i /home/data/test-1080p.mp4 -c:a libfdk_aac -vbr 3 -c:v libx264 -crf 25 -movflags faststart -profile:v baseline -pix_fmt yuv420p -ar 44100 -sws_flags lanczos -vf scale=-2:720 /home/data/test-1080p_720p.mp4
ffmpeg version 4.0.2-2 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8 (Ubuntu 8.2.0-7ubuntu1)
  configuration: --prefix=/usr --extra-version=2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x559dd2bb6c00] st: 1 edit list: 1 Missing key frame while searching for timestamp: 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x559dd2bb6c00] st: 1 edit list 1 Cannot find an index entry before timestamp: 0.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/data/test-1080p.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2019-01-22T14:57:55.000000Z
  Duration: 00:04:03.14, start: 0.000000, bitrate: 2901 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 2771 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2019-01-22T14:57:55.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 01/22/2019.
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      creation_time   : 2019-01-22T14:28:18.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 01/22/2019.
Unknown encoder 'libfdk_aac'
```

**Comment by stefantalpalaru** [comment]
Looks like you don't have fdk-aac support in your ffmpeg. Edit the script to use some other audio codec/library.
